### ISSUE TITLE
Had an issue with chrome/edge specific cookie

### ISSUE THREAD

**Issue by ricardogolez** [browserutils/kooky#54] opened 2022-10-19 10:44 UTC
Error was: Crypto/Cipher: input not full blocks

and it's tracing back to decrypt function when using edge.ReadCookies(fPath)/chrome.ReadCookies(fPath) for ubuntu and windows

function throwing the error: CryptBlocks @ if len(src)%x.BlockSize != 0

**Comment by srlehn** [comment] 2022-10-25 22:08
the "Local State" file is being looked for [1 or 2 directories above](https://github.com/zellyn/kooky/blob/68fd0a98b5210f2697ae98adfa6713798a5e4a92/internal/chrome/chrome_windows.go#L74) the directory of the cookie store - this does not depend on the user.
Chrome [encrypts](https://source.chromium.org/chromium/chromium/src/+/ca9823dd4fc761169b0b760da7c9ad11d13c5ed0:components/os_crypt/os_crypt_win.cc;l=51) cookies on Windows with [CryptProtectData](https://learn.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata) without setting CRYPTPROTECT_LOCAL_MACHINE restricting the [decryption](https://github.com/zellyn/kooky/blob/68fd0a98b5210f2697ae98adfa6713798a5e4a92/internal/chrome/chrome_windows.go#L52) to the current user. The keyrings on Linux also make the decryption user bound.

**Comment by ricardogolez** [comment] 2022-10-25 23:05
Thanks for the reply! I still encounter this issue especially running it on admin

**Comment by srlehn** [comment] 2022-11-04 19:34
For now i believe that you can only get/decrypt a cookie that was created by the same user.

Did you run the browser session that created the cookie also under the admin user?

**Comment by ricardogolez** [comment] 2022-11-05 01:21
No, but the service was running on admin. it works perfectly if the program is run outside program files (tested it on flag commands and also running the service's program on desktop folder).

**Comment by srlehn** [comment] 2023-10-07 11:22
Closing this as not a bug. You have to read the Chrome cookie values under the same user the browser which set those was executed.

**Closed by srlehn** 2023-10-07 11:22 UTC
